#! /bin/bash

# Install homebrew
# Check for Homebrew,
# Install if we don't have it
if test ! $(which brew); then
  echo "Installing homebrew..."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Update homebrew recipes
brew update

# Install cask
brew install caskroom/cask/brew-cask

# Apps

brew cask install iterm2
brew cask install flux
brew cask install google-chrome
brew cask install caffeine
brew cask install lastpass

brew install bash-completion

# Development Apps
# brew cask install java
# brew cask install intellij-idea-ce
# brew cask install boot2docker
# brew install scala

# Config
git config --global push.default simple
git config --global user.name "Brian Hartin"
git config --global user.email brian.hartin@gmail.com

# Convenience
#if test ! $(ls ~/bin); then
#  mkdir ~/bin
#end
